project:
  type: website

website:
  title: "FINE: Fire INcidents Explorer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: overview.qmd
        text: Project Overview
      - href: proposal.qmd
        text: Project Proposal
      - href: user-guide.qmd
        text: User Guide
      - href: poster.qmd
        text: Poster

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

